context01:
  KAFKA_API_KEY: null
  KAFKA_API_SECRET: null
  KAFKA_AUTH_MODULE: PLAINTEXT
  KAFKA_BOOTSTRAP_SERVER: kafka:9092
  KAFKA_SCHEMA_REGISTRY_API_KEY: null
  KAFKA_SCHEMA_REGISTRY_API_SECRET: null
  KAFKA_SCHEMA_REGISTRY_URL: http://schema-registry:8081
